### ISSUE TITLE
Allow for regular contributors to get away with 'infractions'

### ISSUE THREAD

**Issue by orta** [DefinitelyTyped/dt-mergebot#125]
For modules which aren't too popular, and for users who have submitted a lot of PRs (like 20-30+) we could

- Allow with no tests
- Allow other reviewers
- Allow PRs which touch tsconfig or tslint for that project

We could say only allow _1_ of these at a time per PR, and to give at least a day before self merging is allowed.

**Comment by orta** [comment]
Relates to #105  / #98 / #97 / https://github.com/DefinitelyTyped/dt-mergebot/issues/125

**Comment by elibarzilay** [comment]
I went over all of these, and I don't think that there's anything else needed beyond adding code to ignore config file changes that are OK.

**Comment by orta** [comment]
Yeah, we don't need this anymore
