### ISSUE TITLE
'Ready to merge' not working

### ISSUE THREAD

**Issue by Jojoshua** [DefinitelyTyped/dt-mergebot#159]
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46229

**Comment by orta** [comment]
Thanks, I think I know what this is - https://github.com/DefinitelyTyped/dt-mergebot/pull/156 needs to add the PR author to the list of people who can say it

**Comment by elibarzilay** [comment]
Followed things for over a week, and looks like it's working fine now.
