### ISSUE TITLE
People should not be able to self-merge until maintainers of all affected packages have approved a change.

### ISSUE THREAD

**Issue by alloy** [DefinitelyTyped/dt-mergebot#178]
For example, in [this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46473) a maintainer of the `react-native-material-ripple` package approved the changes, but the bulk of the changes were actually in `react-native`, which the author was able to self-merge before a `react-native` maintainer was able to review the changes.

**Comment by alloy** [comment]
There’s now the concept of ‘critical packages’, so this is done afaik.

**Comment by elibarzilay** [comment]
There is, but it bears no implications for accepting a PR -- and actually that's what I'm working on adding right now.

Even when I look at PRs, when there are multiple packages I'd wish there was a mapping of package to owners so I have an idea which packages are fine with the change.  So this will be useful for more than just making self-merges more robust.
