### ISSUE TITLE
PR got auto-merged without owner/maintainer approval

### ISSUE THREAD

**Issue by Maxim-Mazurok** [DefinitelyTyped/dt-mergebot#198]
This PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48335

Was opened by @google-api-typings-generator (my bot account)
The owner was @Bolisov (and he doesn't hang out on GH anymore)
So, I waited patiently for DT maintener to review and merge it.
But then, after fixing the merge conflict, dt-mergebot said that I can "Ready to merge" it and it in fact auto-merged it without owner or maintainer approval, which is probably required in this case.

**Comment by elibarzilay** [comment]
The bot allows approvals from "other"s for packages that don't have more
than 200k monthly downloads, so *your* approval was the one enabling the
self merge.

**Comment by Maxim-Mazurok** [comment]
Hm, in this case I don't understand why it didn't trigger auto-merge the first time I approved this PR. As you can see, there are two approvals from me. And also two approvals from another folk.

**Comment by elibarzilay** [comment]
Merges are triggered when the author or owner explicitly say "ready to merge", not when the approvals are received.

**Comment by Maxim-Mazurok** [comment]
I did say that but deleted my comment later, so I have no proof.
Anyway, why bot didn't say nothing about "Ready to merge" the first time?

**Comment by elibarzilay** [comment]
* You're not the author or the owner, so it wouldn't respond to you saying it.
* I don't know what you mean by "first time".  It said it when the conditions were met: when the merge conflict was resolved and your passing review was noted.

**Comment by Maxim-Mazurok** [comment]
> You're not the author or the owner, so it wouldn't respond to you saying it.

Oh, right, that makes sense.

I think the confusion was because I didn't notice this:
> All of the items on the list are green. To merge, you need to post a comment including the string "Ready to merge" to bring in your changes.

I was looking for this:

> Everything looks good here. Great job! I am ready to merge this PR on your behalf.

Never mind, thanks for explaining!

**Comment by elibarzilay** [comment]
The first "welcome" comment gets updated with that text at the same time the second comment is posted.
