### ISSUE TITLE
Problem with long time to mark a PR abandoned

### ISSUE THREAD

**Issue by elibarzilay** [DefinitelyTyped/dt-mergebot#204]
This is a result of having a month for getting a PR into abandoned state: when a PR was in "waiting for reviews" for a month and got to Abandoned state and therefore on the dt queue --- in this state I hesitate to ping the author or owners since my comment would restart the timer and no maintainers would see it for another month.

I've seen PRs where a maintainer pinged people, and much time passes after that, or where the author tries to ping the owners every 2-3 weeks which leads to PRs that linger for a very long time.

Possible solutions:

* Ignore certain comments (eg, ignore comments from dt maintainers, or comments that contain "ping").  But what about a reply to a ping?  -- It shouldn't reset the counter too.

* Count staleness (either when in a good state or with a failed build) from the last PR update instead of from the last activity.  (But this is a bit ugly since it should only apply for the long timelines.)

* Similar alternative: make the staleness clock go for the short week time if we're a month away from the last pr update -- something like `max(lastActivity + 7days, lastUpdate + 1month)`.  (Where `7days` and `1month` are actually the short and long periods.)

The last one looks best to me.

**Comment by orta** [comment]
I like this last idea too 👍🏻
