### ISSUE TITLE
Suggested timeline changes

### ISSUE THREAD

**Issue by elibarzilay** [DefinitelyTyped/dt-mergebot#208]
### YSYL timeline:

(Currently *one week => NMA*; changes to *one month => closed*.)

- Measure time from when the PR *became mergable* (*excluding* comments etc)
- Wait a week
- Post a ping comment for author (+ owners) with a "JFYI will be closed in 3 weeks if not merged"
- Wait three more weeks (so the total time changes from a week to a *month*)
- not merged yet: apply YSYL label and *close it*
  (this is a change from the previous behavior of putting it on the maintainer NMA queue)

### Unreviewed timeline:

(Currently *one month => NMA*; changes to *two weeks => NMA*.)

- Measured from the *creation time* (including a draft->ready change, or a closed-and-reopened)
- The PR is on either waiting-for-reviews or needs-maintainer-review if there's something to pay attention to
  (in the can be blessed away from NMR to WFR)
- Wait *10 days*
- Post an "unreviewed for over a week" re-ping comment for reviewers
  (do not mention that it will go to NMA, to avoid laziness)
- Wait *1 week*
- Put on NMA (where a maintainer needs to do something)

**Comment by orta** [comment]
Yeah, agree, this sounds good 👍🏻
