### ISSUE TITLE
Inconsistency/Typo: Lifecycle of Pull Request Diagram

### ISSUE THREAD

**Issue by concision** [DefinitelyTyped/dt-mergebot#228]
This issue is overly-pedantic, so feel free to close and ignore it without any changes. I just happened to notice it while reading the DefinitelyTyped documentation and thought it could use a fix.

<hr>

There seems to be a few inconsistencies in lifecycle that is displayed on [`DefinitelyTyped/DefinitelyTyped`](https://github.com/DefinitelyTyped/DefinitelyTyped).

At the bottom left corner,
- it states "You snooze, You ***Loose***" instead of "You snooze, You ***Lose***".
- there is a missing comma on "Stale at 2 days ping at 5 days" that is inconsistent with the 'Abandoned' section above, which has an additional comma (i.e. "Stale at 6 days, ping at 22 days").

I would author a PR to save maintainer time, but I really do not think editing the diagram in Microsoft Paint is better than editing the original source of the image.
<hr>

![mergebot lifecycle](https://raw.githubusercontent.com/DefinitelyTyped/dt-mergebot/master/docs/dt-mergebot-lifecycle.png)

**Comment by elibarzilay** [comment]
Finally fix (as part of a bigger edit) in #251.
