### ISSUE TITLE
Consider ⏳ emoji instead of ❌  for pending 

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [DefinitelyTyped/dt-mergebot#365]
Hi! I love the live comment feature on DT pull requests. It's very useful.

Today was the first time I looked at it immediately after sending a PR and was alarmed for a brief moment at the ❌ s:
 
![Screenshot of typescript-bot informatively commenting on https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51228#issuecomment-778855433](https://user-images.githubusercontent.com/3335181/107891744-9837d600-6eee-11eb-8dd1-37c6caedca0c.png)

Could we switch those to, say, ⏳  to indicate the task is _pending_, not _failed_? I'd be happy to make that change if you're up for it!

**Comment by johnnyreilly** [comment]
I think this is a great suggestion @JoshuaKGoldberg!

**Comment by orta** [comment]
I like it, let's do it

**Comment by elibarzilay** [comment]
The thing is that having these two ⏳✅ icons would look kind of like a wall of graphics and also they're kind of unrelated, no?

Are there better alternatives?  Maybe 🤔😄?  ✋👍?  🔄🆗?  ❓❗?

**Comment by JoshuaKGoldberg** [comment]
Carrying this conversation to its inevitable conclusion:

**Status** 🤔 
* 🙅 ⚔️ 
* 🧪 👍 
* 🕐 😍

**Comment by orta** [comment]
I think the wall clock and then the tick feels great - we can maybe keep the ❌ around for something which is completely out of someone's control
