### ISSUE TITLE
Make discussions on DT better to use than issues

### ISSUE THREAD

**Issue by orta** [DefinitelyTyped/dt-mergebot#421]
In https://github.com/microsoft/TypeScript/issues/44030 one of the big issues with DT is that it's hard to have ecosystem level discussions around DT because the issues generate so much noise. We've migrated the requests for new @types or @types amendments to live inside discussions which comes with a few advantages. 

The discussions however fall prey to the same problem that issues had, mainly that they are hard to stay on top of and most of the time they get no replies.  We're looking at making the same bot which handles the DT workflow also handle augmenting the experience of keeping on top of the DT discussions.

### Feature Plan

- Add support for having the bot @ DT module owners when people make discussions about their modules
- Have a way to ping into the Discord for requests for new DT modules (to somewhat gamify the process)
- Use discussion labels to support following a particular module

WIP PR which adds the bot and sets up most of the above infra: https://github.com/DefinitelyTyped/dt-mergebot/pull/412

**Comment by orta** [comment]
I might have to add support for checking issue comments for this and have them auto-close, I guess there's some GitHub button for doing it as they all seem to have the same syntax:

![Screen Shot 2021-08-13 at 8 26 46 AM](https://user-images.githubusercontent.com/49038/129320501-bf2ee3be-9d96-4ceb-8a04-d9b47a77c664.png)

**Comment by orta** [comment]
The bot is now up and running - https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/55125 is a good example of it in action

**Comment by elibarzilay** [comment]
@orta, is there a way to have other kinds of discussions other than a SO-style Q&A?  (It would look a bit odd if this is used for talking about package bugs etc.)

**Comment by orta** [comment]
Oops missed this, there isn't any config for anything other than this format - no. This does give the poster the ability to 'close' their own issues, handle upvotes etc

**Comment by orta** [comment]
This is solid now
