### ISSUE TITLE
Bot sometimes double-comments

### ISSUE THREAD

**Issue by andrewbranch** [DefinitelyTyped/dt-mergebot#43]
Seeing this a good bit but not 100% of the time. Haven’t figured out the culprit yet as I haven’t reproduced in a test. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44168#issuecomment-622155503

**Comment by andrewbranch** [comment]
Or triple- or quadruple-comments? https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43695#issuecomment-622165830

<img width="775" alt="image" src="https://user-images.githubusercontent.com/3277153/80767574-1280a080-8afd-11ea-947b-d3b57ff2c858.png">

**Comment by orta** [comment]
Ouch, all in the same minute too - I think we need a  0-1500ms delay maybe

**Comment by andrewbranch** [comment]
Ohhh, so your theory is the bot is commenting, which triggers the webhook, and maybe it queries GH again so fast that the GraphQL response doesn’t yet include the latest comment
