### ISSUE TITLE
Update bot’s bio to mention this repo instead of @RyanCavanaugh

### ISSUE THREAD

**Issue by fregante** [DefinitelyTyped/dt-mergebot#462]
I only found this repo by chance and my last ping to Ryan on Twitter went lost

<img width="318" alt="Screenshot" src="https://user-images.githubusercontent.com/1402241/231366687-59ecede7-6c74-46b6-a640-e6bf2eed93ce.png">

**Comment by jakebailey** [comment]
Bio has been updated with a link to the "all the bots" wiki page; this account is used for way more than just this repo.

https://github.com/typescript-bot

![image](https://github.com/DefinitelyTyped/dt-mergebot/assets/5341706/483d858e-c7b6-4126-8a02-c31b8583ee48)

**Comment by fregante** [comment]
Thank you!
