### ISSUE TITLE
Bot is quite eagerly switching columns around

### ISSUE THREAD

**Issue by orta** [DefinitelyTyped/dt-mergebot#7]
What I think is happening is that we get a lot of updates as CI statuses change due to normal processes, which could be triggering switching the columns around.

**Comment by ExE-Boss** [comment]
The bot also considers a queued **Travis CI** build to be failed, when it hasn’t started yet, which is probably related to this.

**Comment by orta** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44299 is as good example of this

**Comment by orta** [comment]
We've discussed the idea that the labels and project board switching should probably only happen a timeout, because the bot is faster than travis to respond.
