### ISSUE TITLE
Consider allowing auto‑merging when the only edited `tsconfig.json` is in the `scripts` directory

### ISSUE THREAD

**Issue by ExE-Boss** [DefinitelyTyped/dt-mergebot#97]
The `scripts` directory doesn’t affect the published package, so I’d expect that changes to it are not considered when determining whether module config files were changed.

## See also:
- <https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45117#issuecomment-635468241>

---

/cc @orta @rbuckton

**Comment by orta** [comment]
Looks like there's only 6 of them, and all of them are on packages which would be considered critically popular and wouldn't be allowed auto-merging anyway I think?

![Screen Shot 2020-06-23 at 5 01 18 PM](https://user-images.githubusercontent.com/49038/85462194-35668880-b573-11ea-868c-301625c6cb38.png)

**Comment by ExE-Boss** [comment]
Well, [`es‑abstract`](https://www.npmjs.com/package/es-abstract) is currently only considered a popular package, not a critical package.

Similarly, [`oibackoff`](https://www.npmjs.com/package/oibackoff) has less than 100 weekly downloads, and [`@types/oibackoff`](https://www.npmjs.com/package/@types/oibackoff) has less than 10.

**Comment by elibarzilay** [comment]
I hesitate to add code that depends on names in the paths: but maybe it should be done...  If `scripts` is common enough as utility functionality then maybe all files in them should be ignored?  Maybe also treat as tests only files that have `test` somewhere in their path following the package name (ie, both `pkg/test/foo.ts` and `pkg/foo-test.ts`)?

**Comment by ExE-Boss** [comment]
@elibarzilay
Why was this issue closed?

**Comment by elibarzilay** [comment]
See the above.  As it is, there's not much actionable stuff here.  A good concrete suggestion would be something along the lines of my last comment above: some path-based facility to classify test files, ignorable files, config files, etc.
